using CoreVault.Accounts.Domain.Enums;
using CoreVault.SharedKernel.Entities;
using CoreVault.SharedKernel.Guards;

namespace CoreVault.Accounts.Domain.Entities;

/// <summary>
/// The Account aggregate root.
/// Represents a bank account owned by a verified customer.
///
/// Key business rules enforced here:
/// 1. Account can only be created for a KYC verified customer
/// 2. Balance can never go negative (overdraft not supported)
/// 3. Frozen accounts block all transactions
/// 4. Closed accounts are immutable — no further changes
/// </summary>
public sealed class Account : AggregateRoot
{
    public Guid CustomerId { get; private set; }
    public string AccountNumber { get; private set; } = string.Empty;
    public AccountType AccountType { get; private set; }
    public AccountStatus Status { get; private set; }
    public decimal Balance { get; private set; }
    public string Currency { get; private set; } = "MYR";
    public decimal InterestRate { get; private set; }
    public decimal DailyTransactionLimit { get; private set; }
    public DateTime? ClosedAt { get; private set; }
    public string? CloseReason { get; private set; }
    public DateTime? LastTransactionAt { get; private set; }

    // Required by EF Core
    protected Account() { }

    private Account(Guid id) : base(id) { }

    /// <summary>
    /// Creates a new bank account.
    /// Account number is generated by the service — not by the caller.
    /// Initial status is PendingActivation until first deposit.
    /// </summary>
    public static Account Open(
        Guid customerId,
        AccountType accountType,
        decimal initialDeposit,
        decimal interestRate,
        decimal dailyTransactionLimit,
        string currency = "MYR")
    {
        Guard.AgainstEmptyGuid(customerId, nameof(customerId));
        Guard.AgainstNegative(initialDeposit, nameof(initialDeposit));
        Guard.AgainstNegative(interestRate, nameof(interestRate));
        Guard.AgainstNegativeOrZero(dailyTransactionLimit,
            nameof(dailyTransactionLimit));

        var account = new Account(Guid.NewGuid())
        {
            CustomerId = customerId,
            AccountNumber = GenerateAccountNumber(),
            AccountType = accountType,
            Status = initialDeposit > 0 ? AccountStatus.Active : AccountStatus.PendingActivation,
            Balance = initialDeposit,
            Currency = currency,
            InterestRate = interestRate,
            DailyTransactionLimit = dailyTransactionLimit
        };

        return account;
    }

    // ── Business Rules ───────────────────────────────────────────

    public bool CanTransact => Status == AccountStatus.Active;

    public bool CanReceiveFunds =>  Status == AccountStatus.Active || Status == AccountStatus.PendingActivation;

    /// <summary>
    /// Credits funds to the account.
    /// Activates a PendingActivation account on first deposit.
    /// </summary>
    public void Credit(decimal amount)
    {
        Guard.AgainstNegativeOrZero(amount, nameof(amount));

        if (Status == AccountStatus.Frozen)
            throw new InvalidOperationException("Cannot credit a frozen account.");

        if (Status == AccountStatus.Closed)
            throw new InvalidOperationException("Cannot credit a closed account.");

        Balance += amount;
        LastTransactionAt = DateTime.UtcNow;

        // Activate on first deposit
        if (Status == AccountStatus.PendingActivation)
            Status = AccountStatus.Active;
    }

    /// <summary>
    /// Debits funds from the account.
    /// Enforces balance check — no overdraft.
    /// </summary>
    public void Debit(decimal amount)
    {
        Guard.AgainstNegativeOrZero(amount, nameof(amount));

        if (!CanTransact)
            throw new InvalidOperationException($"Account cannot transact. Status: {Status}");

        if (amount > Balance)
            throw new InvalidOperationException("Insufficient funds.");

        if (amount > DailyTransactionLimit)
            throw new InvalidOperationException($"Amount exceeds daily transaction limit of {DailyTransactionLimit}.");

        Balance -= amount;
        LastTransactionAt = DateTime.UtcNow;
    }

    public void Freeze(string reason)
    {
        Guard.AgainstNullOrEmpty(reason, nameof(reason));

        if (Status == AccountStatus.Closed)
          throw new InvalidOperationException("Cannot freeze a closed account.");

        Status = AccountStatus.Frozen;
    }

    public void Unfreeze() => Status = AccountStatus.Active;

    public void MarkDormant() =>  Status = AccountStatus.Dormant;

    public void Close(string reason)
    {
        Guard.AgainstNullOrEmpty(reason, nameof(reason));

        if (Status == AccountStatus.Closed)
            throw new InvalidOperationException("Account is already closed.");

        Status = AccountStatus.Closed;
        CloseReason = reason;
        ClosedAt = DateTime.UtcNow;
    }

    // ── Account Number Generation ────────────────────────────────

    /// <summary>
    /// Generates a unique 10-digit account number.
    /// Format: CV + 8 random digits
    /// Example: CV20261234
    /// In production this would use a dedicated sequence
    /// or a centralised account number service.
    /// </summary>
    private static string GenerateAccountNumber()
    {
        var random = new Random();
        var digits = random.Next(10000000, 99999999);
        return $"CV{digits}";
    }
}